# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='選手名')),
                ('yearly_pay', models.IntegerField(verbose_name='年棒')),
                ('position', models.CharField(choices=[('Pitcher', 'pitcher'), ('Catcher', 'catcher'), ('Infielder', 'infielder'), ('Outfielder', 'outfielder')], max_length=32, verbose_name='守備位置')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='球団名')),
            ],
        ),
        migrations.AddField(
            model_name='baseballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Team'),
        ),
    ]
