# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20170526_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballplayer',
            name='position',
            field=models.CharField(max_length=32, verbose_name='守備位置'),
        ),
        migrations.AlterField(
            model_name='baseballplayer',
            name='team',
            field=models.CharField(max_length=32, verbose_name='球団名'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
